#!/bin/bash

# Verify arguments
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 width height camera"
    exit 1
fi

# setting parameters
width=$1
height=$2
camera=$3

# images generations
for angle in $(seq 0 359);
do
    # Format the angle to three digits: ex. angle="1" → angleNNN="001"
    angleNNN=$(printf "%03d" $angle)
    
    # Esegui il comando Julia con i parametri passati
    julia demo $width $height $camera $angle
    
    # Rinomina l'immagine
    mv "demo_${camera}.png" "img$angleNNN.png"
done

# Crea il video con ffmpeg
ffmpeg -r 25 -f image2 -s 640x480 -i img%03d.png -vcodec libx264 -pix_fmt yuv420p spheres-${camera}.mp4
