#!/usr/bin/env julia

#_______________________________________________________________________________________
#     LICENSE NOTICE: European Union Public Licence (EUPL) v.1.2
#     __________________________________________________________
#
#   This file is licensed under the European Union Public Licence (EUPL), version 1.2.
#
#   You are free to use, modify, and distribute this software under the conditions
#   of the EUPL v.1.2, as published by the European Commission.
#
#   Obligations include:
#     - Retaining this notice and the licence terms
#     - Providing access to the source code
#     - Distributing derivative works under the same or a compatible licence
#
#   Full licence text: see the LICENSE file or visit https://eupl.eu
#
#   Disclaimer:
#     Unless required by applicable law or agreed to in writing,
#     this software is provided "AS IS", without warranties or conditions
#     of any kind, either express or implied.
#
#_______________________________________________________________________________________

using Pkg
Pkg.activate(normpath(@__DIR__))

using RayTracer
import Crayons # enables colorful and expressive terminal output

function main()
    try
        # reading parameters from ARGS
        params = RayTracer.Conversion_Params(ARGS)

        # reading image from input file
        img = read_pfm_image(params.input_pfm_file_name)
        println("$(params.input_pfm_file_name) has been read from disk.")
        
        # preparing the image to LDR conversion 
        RayTracer.normalize_image!(img; factor = params.factor, delta = params.delta, mean_type = params.mean_type, weights =params.weights)
        RayTracer.clamp_image!(img)

        # converting the image to LDR format and saving the LDR image on disk
        RayTracer.write_ldr_image(params.output_png_file_name, img; gamma = 1.0)
        println("$(params.output_png_file_name) has been written to disk.")
    
    catch e
        # Define colors for the error message
        red_bold = Crayons.crayon"bold red"  # Bold red text
        reset = Crayons.crayon"reset"        # Reset color to default
        
        # Print the formatted error message
        println(string(red_bold) * "ERROR " * string(reset), "$(typeof(e)): $(e.msg)")
    end
    
end

main()
